name: Edit and Rebase
description: |
  GitHub Action that lets developers edit the commit messages,
  squash them into a single commit, and rebase it on top of the default branch.

runs:
  using: node20
  main: dist/index.js
